dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang++-5.0
            - lcov
        env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - lcov
        env:
          - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

script:
  - cmake --build .

after_success:
  - coveralls --root . -E ".*CMakeFiles.*"