version: 1.0.{build}

image:
- Visual Studio 2017
- Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
- Debug
- Release

environment:
  matrix:
  - USE_SHARED: 0
  - USE_SHARED: 1

before_build:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    Write-Output "Toolset: $env:TOOLSET"
    $generator = switch ($env:TOOLSET)
    {
        "141" {"Visual Studio 15 2017"}
        "140" {"Visual Studio 14 2015"}
    }

build_script:
- ps: |
    md build -Force | Out-Null
    cd build
    & cmake -G "$generator" -DUSE_SHARED=%USE_SHARED% -Dgtest_build_tests=OFF -Dgtest_build_samples=OFF -Dgmock_build_tests=OFF ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
  
test_script:
- ps: |
    ctest -C $env:CONFIGURATION --output-on-failure
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
  
artifacts:
  - path: build
    name: build
